### ISSUE TITLE
使用后文件未解密，发送至其他客户端打开显示文件损坏。

### ISSUE THREAD

**Issue by cnzshadowt** [zhang00lei/YiSaiTongUnLock#1]
如题，求大佬指导一下，谢谢

**Comment by zhang00lei** [comment]
呃，你这问题描述的很宽泛呢

**Comment by cnzshadowt** [comment]
不太懂编程，提示解密成功，但是未解密，我也很奇怪，不知道哪里的问题。&nbsp;


刘帅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月24日(星期五) 下午3:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhang00lei/YiSaiTongUnLock] 使用后文件未解密，发送至其他客户端打开显示文件损坏。 (Issue #1)





 
呃，你这问题描述的很宽泛呢

**Comment by zhang00lei** [comment]
> 不太懂编程，提示解密成功，但是未解密，我也很奇怪，不知道哪里的问题。&nbsp; 刘帅 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年3月24日(星期五) 下午3:42 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [zhang00lei/YiSaiTongUnLock] 使用后文件未解密，发送至其他客户端打开显示文件损坏。 (Issue #1) 呃，你这问题描述的很宽泛呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

按照描述的步骤即可，不行的话，留下邮箱，私

**Comment by cnzshadowt** [comment]
我是按照操作步骤进行的，提示解密成功，但是还是上锁的状态，我的邮箱是576299693@qq.com，谢谢大佬

**Comment by zssir** [comment]
> > 不太懂编程，提示解密成功，但是未解密，我也很奇怪，不知道哪里的问题。  刘帅 _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年3月24日(星期五) 下午3:42 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [zhang00lei/YiSaiTongUnLock] 使用后文件未解密，发送至其他客户端打开显示文件损坏。 (Issue #1) 呃，你这问题描述的很宽泛呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 按照描述的步骤即可，不行的话，留下邮箱，私

大佬，遇到相同问题，求指导 448365456@qq.com

**Comment by zhang00lei** [comment]
> 



> > > 不太懂编程，提示解密成功，但是未解密，我也很奇怪，不知道哪里的问题。  刘帅 _**@**_.***  
> > > […](#)
> > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年3月24日(星期五) 下午3:42 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [zhang00lei/YiSaiTongUnLock] 使用后文件未解密，发送至其他客户端打开显示文件损坏。 (Issue #1) 呃，你这问题描述的很宽泛呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > 
> > 
> > 按照描述的步骤即可，不行的话，留下邮箱，私
> 
> 大佬，遇到相同问题，求指导 [448365456@qq.com](mailto:448365456@qq.com)

可能当前的这个应用程序不适应于你们公司设置的亿赛通策略，需要另外再找解决方案

**Comment by zssir** [comment]
> > 
> 
> > > > 不太懂编程，提示解密成功，但是未解密，我也很奇怪，不知道哪里的问题。  刘帅 _**@**_.***  
> > > > […](#)
> > > > ------------------ 原始邮件 ------------------ 发件人: _**@**_._**>; 发送时间: 2023年3月24日(星期五) 下午3:42 收件人: _**@**_.**_>; 抄送: _**@**_._**>; _**@**_.**_>; 主题: Re: [zhang00lei/YiSaiTongUnLock] 使用后文件未解密，发送至其他客户端打开显示文件损坏。 (Issue #1) 呃，你这问题描述的很宽泛呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> > > 
> > > 
> > > 按照描述的步骤即可，不行的话，留下邮箱，私
> > 
> > 
> > 大佬，遇到相同问题，求指导 [448365456@qq.com](mailto:448365456@qq.com)
> 
> 可能当前的这个应用程序不适应于你们公司设置的亿赛通策略，需要另外再找解决方案

当前公司的策略是，文件在创建、修改、移动路径等场景下都会被自动加密，所以猜测文件在解密打开生成未加密文件时又被自动加密了
