### ISSUE TITLE
不能使用啊，提示缺exe 

### ISSUE THREAD

**Issue by ZhangYHui** [zhang00lei/YiSaiTongUnLock#2]
![image](https://github.com/zhang00lei/YiSaiTongUnlock/assets/7855810/ad44db06-ba16-429c-b256-a91f93f7c5d7)

**Comment by zhang00lei** [comment]
把[UnlockAll](https://github.com/zhang00lei/YiSaiTongUnlock/tree/main/UnlockAll)项目编译完成后为UnlockAll.exe，
把[UnlockFile](https://github.com/zhang00lei/YiSaiTongUnlock/tree/main/UnlockFile)项目编译完成后改为wps.exe。
再通过innosetup编译打包。
你也可以直接使用release，但是这个解密方法并不是对所有公司策略有效。

**Comment by ZhangYHui** [comment]
您的来信我收到~~ 张宇卉

**Comment by yang02-ctal** [comment]
> 把[UnlockAll](https://github.com/zhang00lei/YiSaiTongUnlock/tree/main/UnlockAll)项目编译完成后为UnlockAll.exe， 把[UnlockFile](https://github.com/zhang00lei/YiSaiTongUnlock/tree/main/UnlockFile)项目编译完成后改为wps.exe。 再通过innosetup编译打包。 你也可以直接使用release，但是这个解密方法并不是对所有公司策略有效。

怎么编译go文件呢，，

**Comment by ZhangYHui** [comment]
您的来信我收到~~ 张宇卉
